title: Bhaswan G
logo: /assets/Logo%20500x500%20px.jpeg
description: About Me
Hey there! I'm all about diving headfirst into the world of computers and science. It's like this endless adventure where every discovery leads to another question. 🌟
You'll usually find me buried in my laptop, tinkering with code and exploring the wonders of computer science. I've been getting my hands dirty with stuff like Fortran, Linux, and Arduino, just trying to soak up as much knowledge as I can.
Arduino, in particular, has been a real game-changer for me. I've been cooking up all sorts of projects with it, from simple circuits to more complex setups. It's like being a mad scientist in my own little lab!
But it's not all about computers for me. I've got a serious love affair with science, especially physics. There's something about the way the universe works that blows my mind every time. I'm always down for a good experiment or a deep dive into some mind-bending theory.
And hey, when I'm not knee-deep in code or staring up at the stars, you can probably find me doodling away on my tablet. Graphic design is my way of bringing a little bit of creativity into everything I do.
So yeah, that's me in a nutshell – a curious soul with a passion for all things tech, science, and creativity. Here's to never-ending discoveries and endless possibilities!
show_downloads: true
theme: jekyll-theme-minimal
